<?php

return [
    'cron_token' => env('VERGO_CRON_TOKEN', ''),
    'property_object_types' => [
        'apartment',
        'office',
        'retail_unit',
        'storage',
        'parking',
        'technical_room',
        'common_area',
        'other',
    ],
    'property_usage_types' => [
        'residential',
        'commercial',
        'mixed',
    ],
    'job_types' => [
        'cleaning',
        'hvac_maintenance',
        'elevator_service',
        'electrical',
        'plumbing',
        'security',
        'landscaping',
        'flooring',
        'painting',
        'one_time_repair',
        'general_maintenance',
        'other',
        'elektro',
        'gebaeudeautomation_schwachstrom_kommunikation',
        'heizung',
        'lueftung',
        'klima_kaelte',
        'sanitaer',
        'maler',
        'gipser_trockenbau',
        'bodenbelaege',
        'plattenleger',
        'schreiner_innenausbau',
        'metallbau_schloss_beschlaege',
        'fenster_glas_storen_sonnenschutz',
        'dach_spengler_flachdach',
        'fassade_gebaeudehuelle',
        'maurer_beton_kernbohrung',
        'reinigung',
        'garten_umgebung_winterdienst',
        'kanal_entwaesserung',
        'kueche_geraete_haushaltstechnik',
        'lift',
        'brandschutz_sicherheit',
        'holzbau_zimmermann',
        'solar_photovoltaik_solarthermie',
        'tuer_tor_garagentor',
        'geruestbau',
        'schadstoffsanierung_rueckbau',
        'raeumung_entsorgung',
    ],
    'job_type_labels' => [
        'cleaning' => 'Reinigung',
        'hvac_maintenance' => 'Heizung / Lüftung / Klima',
        'elevator_service' => 'Lift',
        'electrical' => 'Elektro',
        'plumbing' => 'Sanitär',
        'security' => 'Sicherheit / Schwachstrom',
        'landscaping' => 'Garten / Umgebung / Winterdienst',
        'flooring' => 'Bodenbeläge / Plattenleger',
        'painting' => 'Maler',
        'one_time_repair' => 'Einmalige Reparatur',
        'general_maintenance' => 'Allgemeiner Unterhalt',
        'other' => 'Sonstiges',
        'elektro' => 'Elektro',
        'gebaeudeautomation_schwachstrom_kommunikation' => 'Gebäudeautomation / Schwachstrom / Kommunikation',
        'heizung' => 'Heizung',
        'lueftung' => 'Lüftung',
        'klima_kaelte' => 'Klima / Kälte',
        'sanitaer' => 'Sanitär',
        'maler' => 'Maler',
        'gipser_trockenbau' => 'Gipser / Trockenbau',
        'bodenbelaege' => 'Bodenbeläge',
        'plattenleger' => 'Plattenleger',
        'schreiner_innenausbau' => 'Schreiner / Innenausbau',
        'metallbau_schloss_beschlaege' => 'Metallbau / Schloss / Beschläge',
        'fenster_glas_storen_sonnenschutz' => 'Fenster / Glas / Storen / Sonnenschutz',
        'dach_spengler_flachdach' => 'Dach / Spengler / Flachdach',
        'fassade_gebaeudehuelle' => 'Fassade / Gebäudehülle',
        'maurer_beton_kernbohrung' => 'Maurer / Beton / Kernbohrung',
        'reinigung' => 'Reinigung',
        'garten_umgebung_winterdienst' => 'Garten / Umgebung / Winterdienst',
        'kanal_entwaesserung' => 'Kanal / Entwässerung',
        'kueche_geraete_haushaltstechnik' => 'Küche / Geräte / Haushaltstechnik',
        'lift' => 'Lift',
        'brandschutz_sicherheit' => 'Brandschutz / Sicherheit',
        'holzbau_zimmermann' => 'Holzbau / Zimmermann',
        'solar_photovoltaik_solarthermie' => 'Solar / Photovoltaik / Solarthermie',
        'tuer_tor_garagentor' => 'Tür / Tor / Garagentor',
        'geruestbau' => 'Gerüstbau',
        'schadstoffsanierung_rueckbau' => 'Schadstoffsanierung / Rückbau',
        'raeumung_entsorgung' => 'Räumung / Entsorgung',
    ],
];
