<?php

return [
    'cron_token' => env('VERGO_CRON_TOKEN', ''),
    'property_object_types' => [
        'apartment',
        'office',
        'retail_unit',
        'storage',
        'parking',
        'technical_room',
        'common_area',
        'other',
    ],
    'property_usage_types' => [
        'residential',
        'commercial',
        'mixed',
    ],
    'job_types' => [
        'cleaning',
        'hvac_maintenance',
        'elevator_service',
        'electrical',
        'plumbing',
        'security',
        'landscaping',
        'flooring',
        'painting',
        'one_time_repair',
        'general_maintenance',
        'other',
        'elektro',
        'gebaeudeautomation_schwachstrom_kommunikation',
        'heizung',
        'lueftung',
        'klima_kaelte',
        'sanitaer',
        'maler',
        'gipser_trockenbau',
        'bodenbelaege',
        'plattenleger',
        'schreiner_innenausbau',
        'metallbau_schloss_beschlaege',
        'fenster_glas_storen_sonnenschutz',
        'dach_spengler_flachdach',
        'fassade_gebaeudehuelle',
        'maurer_beton_kernbohrung',
        'reinigung',
        'garten_umgebung_winterdienst',
        'kanal_entwaesserung',
        'kueche_geraete_haushaltstechnik',
        'lift',
        'brandschutz_sicherheit',
        'holzbau_zimmermann',
        'solar_photovoltaik_solarthermie',
        'tuer_tor_garagentor',
        'geruestbau',
        'schadstoffsanierung_rueckbau',
        'raeumung_entsorgung',
    ],
];
